# Generated by Django 4.0.6 on 2022-11-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('ctitle', models.CharField(max_length=75)),
                ('cfeedback', models.TextField()),
                ('cfdate', models.DateTimeField(auto_now=True)),
                ('cfdatemodification', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
