# Generated by Django 4.0.6 on 2022-11-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testiminal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestiminalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('ctitle', models.CharField(max_length=75)),
                ('cemail', models.CharField(max_length=30)),
                ('cphone', models.CharField(max_length=10)),
                ('cfeedback', models.TextField()),
                ('cfdate', models.DateTimeField(auto_now=True)),
                ('cfdatemodification', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
