# Generated by Django 4.0.6 on 2022-11-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testiminal', '0002_testiminalmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestimModel',
        ),
    ]
