# Generated by Django 4.0.6 on 2022-10-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogshort',
            name='web_link',
            field=models.CharField(max_length=250),
        ),
    ]
