# Generated by Django 4.0.6 on 2022-10-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_delete_blog_dis_delete_blogshort'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='blog_overview/')),
                ('title', models.CharField(max_length=250)),
                ('discription', models.TextField()),
            ],
        ),
    ]
