# Generated by Django 4.0.6 on 2022-10-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogShort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='blog_overview/')),
                ('title', models.CharField(max_length=150)),
                ('discription', models.TextField()),
                ('web_link', models.CharField(max_length=250)),
            ],
        ),
    ]
