# Generated by Django 4.0.6 on 2022-12-23 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_blogshort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogshort',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=250, null=True, upload_to='media/blog_overview'),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, max_length=250, null=True, upload_to='media/blog_overview')),
                ('title', models.CharField(max_length=150)),
                ('discription', models.TextField()),
                ('web_link', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
