# Generated by Django 4.0.6 on 2022-12-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogDis',
        ),
        migrations.DeleteModel(
            name='BlogShort',
        ),
    ]
