# Generated by Django 4.0.6 on 2022-12-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_blogdis_delete_blogshort'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Umessage', models.TextField()),
                ('uname', models.CharField(max_length=50)),
                ('uemail', models.EmailField(max_length=30)),
            ],
        ),
    ]
