# Generated by Django 4.0.6 on 2023-01-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_commentmodel_delete_commentsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='created_on',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
