# Generated by Django 4.0.6 on 2023-01-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blogpost_created_on_blogpost_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
