# Generated by Django 4.0.6 on 2022-09-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=None, max_length=250, upload_to='Natural/')),
                ('subdetails', models.CharField(max_length=250)),
                ('details', models.TextField()),
            ],
        ),
    ]
