# Generated by Django 4.0.6 on 2022-09-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_naturaldata_subdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturaldata',
            name='subdetails',
            field=models.TextField(max_length=250),
        ),
    ]
