# Generated by Django 4.0.6 on 2022-10-09 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_naturaldata_subdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NaturalData',
        ),
    ]
