# Generated by Django 4.0.6 on 2022-11-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestarea',
            name='image',
            field=models.ImageField(upload_to='interestImg/'),
        ),
    ]
