# Generated by Django 4.0.6 on 2022-11-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_interestarea_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_image', models.ImageField(upload_to='img/projectImg/')),
                ('proj_title', models.CharField(max_length=100)),
                ('proj_descript', models.TextField()),
            ],
        ),
    ]
