# Generated by Django 4.0.6 on 2022-12-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_fearturemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeartureSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeaImage', models.ImageField(upload_to='img/feature/')),
                ('FeaTitle', models.CharField(max_length=100)),
                ('FeaDescript', models.TextField()),
            ],
        ),
    ]
