# Generated by Django 4.0.6 on 2022-12-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_fearturesectionmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeartureSectionModel',
        ),
    ]
