# Generated by Django 4.0.6 on 2022-12-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_fearturesectionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeartureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeaImage', models.ImageField(upload_to='img/feature/')),
                ('FeaTitle', models.CharField(max_length=100)),
                ('FeaDescript', models.TextField()),
                ('FeaWebLink', models.URLField(blank=True, default=None, null=True)),
            ],
        ),
    ]
