# Generated by Django 4.0.6 on 2022-12-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_fearturesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fearturesection',
            name='FeaWebLink',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
