# Generated by Django 4.0.6 on 2022-12-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_fearturesection_feaweblink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeartureModel',
        ),
    ]
