# Generated by Django 4.0.6 on 2023-01-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_projectmodel1_delete_projectmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_image', models.ImageField(upload_to='img/projectImg/')),
                ('proj_title', models.CharField(max_length=100)),
                ('proj_descript', models.TextField()),
                ('proj_link', models.URLField()),
            ],
        ),
    ]
