# Generated by Django 4.0.6 on 2023-01-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_projectmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectModel1',
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='proj_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
