# Generated by Django 4.1.5 on 2023-01-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_delete_projectmodel1_alter_projectmodel_proj_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fearturesection",
            name="FeaImage",
            field=models.ImageField(upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="interestarea",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
