# Generated by Django 4.0.6 on 2022-12-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDataLearn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('CourseImage', models.ImageField(upload_to='image/courseImg')),
                ('description', models.TextField()),
                ('web_link_learn', models.URLField()),
            ],
        ),
    ]
