# Generated by Django 4.0.6 on 2022-12-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_coursedatalearn'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLearn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('CourseImage', models.ImageField(upload_to='image/courseImg')),
                ('description', models.TextField()),
                ('web_link_learn', models.URLField(default=None, null=True)),
                ('video_learn', models.URLField(default=None, null=True)),
                ('scription_learn', models.URLField(default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CourseDataLearn',
        ),
    ]
