# Generated by Django 4.0.6 on 2022-12-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_courselearn_delete_coursedatalearn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseData',
        ),
        migrations.AlterField(
            model_name='courselearn',
            name='scription_learn',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='courselearn',
            name='video_learn',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='courselearn',
            name='web_link_learn',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
