# Generated by Django 4.0.6 on 2022-12-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_trendingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/trending/')),
                ('weblink', models.URLField(blank=True, default=None, null=True)),
            ],
        ),
    ]
