# Generated by Django 4.0.6 on 2022-12-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_alter_trending_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingmodel',
            name='weblink',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
