# Generated by Django 4.0.6 on 2022-12-10 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_trendingmodel_weblink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trending',
        ),
    ]
