# Generated by Django 4.0.6 on 2023-01-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0011_alter_courselearn_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselearn',
            name='CourseImage',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='courselearn',
            name='description',
            field=models.TextField(),
        ),
    ]
