# Generated by Django 4.0.6 on 2023-01-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0012_alter_courselearn_courseimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselearn',
            name='doc_link_learn',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
