# Generated by Django 4.1.5 on 2023-01-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0013_courselearn_doc_link_learn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trendingmodel",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
