# Generated by Django 4.1.5 on 2023-03-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0014_alter_trendingmodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courselearn",
            name="CourseImage",
            field=models.ImageField(upload_to="image/courseImg"),
        ),
    ]
