# Generated by Django 4.0.6 on 2023-01-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resumes',
            field=models.FileField(upload_to='media/'),
        ),
    ]
