# Generated by Django 4.0.6 on 2023-01-03 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.FileField(upload_to='media/profile_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_img_Form',
            fields=[
                ('userimg_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deshboard.userimg')),
            ],
            bases=('deshboard.userimg',),
        ),
    ]
