# Generated by Django 4.0.6 on 2023-01-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deshboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimg',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='userimg',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/profile_img/'),
        ),
        migrations.DeleteModel(
            name='Profile_img_Form',
        ),
    ]
