# Generated by Django 4.0.6 on 2023-01-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deshboard', '0003_alter_userimg_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimg',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/profile_img/'),
        ),
    ]
