# Generated by Django 4.0.6 on 2023-01-04 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deshboard', '0004_alter_userimg_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProUserImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/profile_img/')),
                ('profile_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProUserImg', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserImg',
        ),
    ]
