# Generated by Django 4.0.6 on 2023-01-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deshboard', '0007_remove_prouserimg_profile_name_alter_prouserimg_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prouserimg',
            name='file',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
