# Generated by Django 4.1.5 on 2023-08-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deshboard", "0008_alter_prouserimg_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProUserImg",
        ),
    ]
